[package]
name = "roselib"
version = "0.3.0"
authors = ["Ralph Minderhoud <ralphminderhoud@gmail.com>"]
homepage = "ralphminderhoud.com"

[dependencies]
byteorder = "1.2"
failure = "0.1"
num = "0.1"
num-derive = "0.2"
num-traits = "0.2"
serde = "1.0"
serde_derive = "1.0"
